version: '3.8'

services:
  app:
    build: .
    environment:
      - MONGODB_URL=mongodb://root:example@mongodb:27017/
      - DB_NAME=users_db
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongodb_data:/data/db

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  mongodb_data: